/**
 * Shared mock hazard markers representing real civic reports across the corridor.
 */
export const MARKERS = [
  {
    id: "rep-001",
    title: "Deep Pothole Cluster & Asphalt Crumble",
    category: "Pothole",
    severity: "CRITICAL",
    status: "UNDER_REVIEW",
    latitude: 28.4982,
    longitude: 77.0891,
    road_name: "NH-48 Corridor (Cyber City Exit)",
    route_proximity: "fastest",
    impact_score: 25,
  },
  {
    id: "rep-002",
    title: "Monsoon Waterlogging & Silted Drain Grate",
    category: "Drainage",
    severity: "HIGH",
    status: "FORWARDED",
    latitude: 28.4895,
    longitude: 77.0854,
    road_name: "IFFCO Chowk Flyover Underpass",
    route_proximity: "fastest",
    impact_score: 20,
  },
  {
    id: "rep-003",
    title: "Surface Sub-base Depression",
    category: "Pothole",
    severity: "HIGH",
    status: "ASSIGNED",
    latitude: 28.4764,
    longitude: 77.0712,
    road_name: "Rajiv Chowk Service Lane",
    route_proximity: "fastest",
    impact_score: 18,
  },
  {
    id: "rep-004",
    title: "Blown Streetlight Grid & Dark Zone",
    category: "Lighting",
    severity: "MEDIUM",
    status: "WORK_PLANNED",
    latitude: 28.4682,
    longitude: 77.0543,
    road_name: "Sector 31 Connector Road",
    route_proximity: "fastest",
    impact_score: 10,
  },
  {
    id: "rep-005",
    title: "Cavity Formation near Storm Channel",
    category: "Pothole",
    severity: "CRITICAL",
    status: "UNDER_REVIEW",
    latitude: 28.4551,
    longitude: 77.0398,
    road_name: "Medanta Transit Expressway",
    route_proximity: "fastest",
    impact_score: 22,
  },
  {
    id: "rep-006",
    title: "Minor Surface Hairline Cracking",
    category: "Pothole",
    severity: "LOW",
    status: "SUBMITTED",
    latitude: 28.4621,
    longitude: 77.1054,
    road_name: "Golf Course Extension Link Road",
    route_proximity: "recommended",
    impact_score: 4,
  },
  {
    id: "rep-007",
    title: "Dislodged Curb Stone",
    category: "Other",
    severity: "LOW",
    status: "SUBMITTED",
    latitude: 28.4418,
    longitude: 77.0982,
    road_name: "Southern Peripheral Sector 65 Entry",
    route_proximity: "recommended",
    impact_score: 4,
  },
];
